title: Alignment Credit
timezone: America/New_York
url: http://alignmentcredit.com
description: Alignment Credit provides credit financing solutions for emerging growth & middle-market companies.
collections:
  posts:
    title: Posts
    output: false
  uploads:
    title: Uploads
    output: true
  case_studies:
    title: Case Studies
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: case_studies
  values:
    permalink: "/portfolio/:title/"
    layout: case_study
    investment:
    - 
    value-add:
    - 
    link: 
    image: 
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README*
- '.gitignore'
plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-seo-tag
twitter:
  username: alignmentcredit
logo: /assets/images/avatar.png
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge
excerpt_separator: |2+



sass:
  sass_dir: assets/styles/
  style: compressed
repository: justinjaywang/alignmentcredit.com
google_analytics: 
date_format: "%b %-d, %Y"
nav:
  header:
  - text: Our Advantage
    link: /about/debt-vs-equity/
  - text: Case Studies
    link: /portfolio/
recent_posts: 3
about_pages:
- Debt vs. Equity
- Partnering with Alignment
- Target Investments
contact:
  email: info@alignmentcredit.com
  address: |-
    73 Spring Street, Suite 207<br>
    New York, NY 10012
  map_link: https://goo.gl/maps/jrZjJSh7tUE2
