---
title: Alignment Credit
timezone: America/New_York
collections:
  case_studies:
    title: Case Studies
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: case_studies
  values:
    link: 
    image: 
    items:
    - title: Ownership
      content: 
    - title: Total Commitment
      content: 
    - title: Structure
      content: 
    - title: Use of Proceeds
      content: "- "
    - title: Alignment Role
      content: Joint lender with Prudential Impact Investments
    - title: Key Features
      content: "- "
    - title: Alignment Value-Add
      content: "- "
url: http://alignmentcredit.com
description: Alignment Credit provides credit financing solutions for emerging growth
  & middle-market companies.
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README*
- ".gitignore"
- node_modules
plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-seo-tag
twitter:
  username: alignmentcredit
logo: "/assets/images/avatar.png"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge
excerpt_separator: |2+



sass:
  sass_dir: assets/styles/
  style: compressed
repository: justinjaywang/alignmentcredit.com
google_analytics: UA-112023605-1
date_format: "%b %-d, %Y"
nav:
- title: Our Advantage
  link: "/about/debt-vs-equity/"
- title: Our Portfolio
  link: "/portfolio/recent-transactions"
num_recent_posts: 3
contact:
  email: info@alignmentcredit.com
  address: |-
    73 Spring Street, Suite 207<br>
    New York, NY 10012
  map_link: https://goo.gl/maps/jrZjJSh7tUE2
